Initialized project Back&Front structure
SiMDE-Projects/sparkle pull request #3
Opened 2022-02-07 11:30 UTC by cesar-richard

2022-02-07 12:15 UTC, mael-belval requested changes
- Quelques changements sur le JS
- Ajout de SCSS ou pas ?
- Quelques questions éparses

2022-02-07 12:15 UTC, mael-belval commented on sparkle/api/utils.py
> +        abstract = True
Ajouter un peu de doc ? Ne faisant pas de python, je suis pas sur de tout ce qui se passe ici

2022-02-07 12:15 UTC, mael-belval commented on sparkle/frontend/src/App.js
> +const App = function () {
Fonction fléchée ici non ?

2022-02-07 12:15 UTC, mael-belval commented on sparkle/frontend/src/index.js
> +)
ESLint AirBNB requiert des point-virgules non ?

2022-02-07 12:15 UTC, mael-belval commented on sparkle/frontend/src/index.js
> +import "semantic-ui-css/semantic.min.css"
ESLint AirBNB => Apostrophe

2022-02-07 12:15 UTC, mael-belval commented on sparkle/frontend/templates/frontend/index.html
> +<html lang="en">
en ?

2022-02-07 12:50 UTC, cesar-richard commented on package.json
> +}
> * Quelques changements sur le JS
> * Ajout de SCSS ou pas ?
> * Quelques questions éparses

C'est un init. On affinera plus tard.

2022-02-07 12:51 UTC, cesar-richard commented on sparkle/frontend/src/index.js
> +import "semantic-ui-css/semantic.min.css"
init, a revoir

2022-02-07 12:51 UTC, cesar-richard commented on sparkle/frontend/templates/frontend/index.html
> +<html lang="en">
init, a revoir

2022-02-07 12:51 UTC, cesar-richard commented on webpack.config.js
> +}
init, a revoir

2022-02-07 12:53 UTC, R0one commented on package.json
> +}
je ne sais pas encore quelles specs césar a en tête, mais pour moi c'est une techno très peu complexe (accessible) qui rend le code plus factorisé (donc plus petit, donc plus lisible, donc plus accessible), et je crois que ce n'est pas très gênant d'ajouter encore un peu plus de magie noire dans le compilateur web. Mais j'ai très peu d'expérience. C'est peut-être un sujet à aborder en STP.

2022-02-07 21:17 UTC, mael-belval approved these changes

2022-02-07 21:26 UTC, merged

2022-02-07 21:32 UTC, noeamiot commented on README.md
> +One the project is initialized, you can go to theses urls to work:
Once non ?

2022-02-07 21:32 UTC, noeamiot commented on README.md
> +Pull requests not complying with code repository's format and style rules would be marked as stall until it's fixed.
will be marked as stall until fixed.

2022-02-10 16:47 UTC, R0one commented on docker-compose.yml
> +      - "3306:3306"
est-ce vraiment utile de se bind sur l'hôte docker (et sur un port privilégié)? J'imagine que le service sql est consommé seulement par la prod web, qui est dockerisée, donc il y aurait moyen de passer par des networks docker (et de ne pas bind sur le 0.0.0.0:3306 de l'hôte)

2022-02-10 17:12 UTC, R0one commented on docker-compose.yml
> +      - "3306:3306"
> Non la prod n'est pas dockerisée, le docker ne sert que d'environnement reproductible de dev. Pour facilier ce dev j'expose 2 facons d'aller fouiller la DB si besoin, soit via un conteneur adminer disponnible dans le profile de lancement "debug" 
soit via un autre client SQL de ton choix (perso j'utilise le client intégré à PyCharm, et donc quitte à exposer un port pour m'y connecter il me parraissait logique de prendre le vrai port)
Enfin, non, 3306 n'est pas un port à accès privilegié

2022-02-10 18:35 UTC, cesar-richard commented
Test de notif WebHook sur commentaire sur PR merged

2022-02-10 18:37 UTC, cesar-richard commented
Test de notif WebHook sur commentaire sur PR merged